# Generated by Django 5.2.5 on 2025-09-03 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('text', 'Text Entry'), ('voice', 'Voice Note'), ('quick', 'Quick Note')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='word_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(choices=[('😊', 'Happy'), ('😢', 'Sad'), ('😐', 'Neutral'), ('😡', 'Angry'), ('😴', 'Tired'), ('😨', 'Anxious'), ('😌', 'Peaceful'), ('😔', 'Reflective'), ('😤', 'Frustrated'), ('🤗', 'Grateful')], default='😐', max_length=2),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
